### ISSUE TITLE
ModuleNotFoundError: No module named 'win32com'

### ISSUE THREAD

**Issue by wzk1996** [bode135/pydamo#1]
我运行项目的时候，会报错
内容如下
pydev debugger: process 9036 is connecting

Connected to pydev debugger (build 193.6911.25)
注册dm.dll
Traceback (most recent call last):
  File "D:\Project\Python\Exercice\pydamo\damo.py", line 7, in __init__
    from win32com.client import Dispatch
ModuleNotFoundError: No module named 'win32com'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Program\SDK\Pycharm\PyCharm 2019.3.4\plugins\python\helpers\pydev\pydevd.py", line 1434, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "D:\Program\SDK\Pycharm\PyCharm 2019.3.4\plugins\python\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "D:/Project/Python/Exercice/pydamo/简单案例.py", line 11, in <module>
    dm = DM()
  File "D:\Project\Python\Exercice\pydamo\damo.py", line 14, in __init__
    self.dm = Dispatch('dm.dmsoft')  # 调用大漠插件
UnboundLocalError: local variable 'Dispatch' referenced before assignment

但是找不到win32com这个依赖，要怎么解决呢

**Comment by bode135** [comment]
试一试:
pip install pywin32
这一段是注册和绑定dm.dll，win32com需要pywin32依赖项。
解释器必须是32位的python

**Comment by wzk1996** [comment]
(py37_32) D:\Project\Python\Exercice\pydamo> python
Python 3.7.7 (default, Mar 23 2020, 23:04:27) [MSC v.1916 32 bit (Intel)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> exit()

(py37_32) D:\Project\Python\Exercice\pydamo>pip install pywin32
Requirement already satisfied: pywin32 in d:\program\sdk\anaconda\envs\py37_32\lib\site-packages (227)

我看了一下，python是32位的，pywin32也安装了，但是还是不行

**Comment by bode135** [comment]
那试试在cmd中使用python -m pip install pypiwin32进行安装吧
或者试试pip install pypiwin32

**Comment by wzk1996** [comment]
应该是pywin32的位数不对，我的解决方法是通过浏览器下载pywin32，然后手动安装
pywin32下载地址https://www.lfd.uci.edu/~gohlke/pythonlibs/#pywin32
选择pywin32‑227‑cp37‑cp37m‑win32.whl（具体版本根据情况选择）
然后cmd进入该文件的文件夹下，使用下列命令安装
pip install pywin32-227-cp37-cp37m-win32.whl
希望对有需要的人提供一点帮助

**Comment by bode135** [comment]
谢谢填坑~

**Comment by fairetamere** [comment]
我在pycharm中运行，绑定窗口时会报错Process finished with exit code -1073741819 (0xC0000005)，指点，这是什么灵异情况，另外枚举窗口等函数都可以正常使用，望指教

**Comment by bode135** [comment]
(0xC0000005)我记得有反应过...你需要以管理员权限运行pycharm




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "fairetamere"<notifications@github.com&gt;; 
发送时间: 2020年4月21日(星期二) 晚上7:47
收件人: "bode135/pydamo"<pydamo@noreply.github.com&gt;; 
抄送: "博得"<2248270222@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [bode135/pydamo] ModuleNotFoundError: No module named &#39;win32com&#39; (#1)





 
我在pycharm中运行，绑定窗口时会报错Process finished with exit code -1073741819 (0xC0000005)，指点，这是什么灵异情况，另外枚举窗口等函数都可以正常使用，望指教

**Comment by fairetamere** [comment]
嗯 谢谢 我试试 感谢大佬

**Comment by fairetamere** [comment]
貌似还是不行。。。。。

**Comment by fairetamere** [comment]
跟pycharm版本有关系吗

**Comment by bode135** [comment]
应该没关系... 用不了后台就用前台吧, 后台的我也用得不是很明白...



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "fairetamere"<notifications@github.com&gt;; 
发送时间: 2020年4月21日(星期二) 晚上8:10
收件人: "bode135/pydamo"<pydamo@noreply.github.com&gt;; 
抄送: "博得"<2248270222@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [bode135/pydamo] ModuleNotFoundError: No module named &#39;win32com&#39; (#1)





 
跟pycharm版本有关系吗

**Comment by fairetamere** [comment]
就想弄明白 前台用起来太蛋疼了 还是谢谢大佬

**Comment by bode135** [comment]
如果不是管理员权限的问题的话,可能的问题也就注册码的问题了...
后台模拟功能是收费的...
可能是我的这个注册码里面没钱了, 你可以看看damo.py里面Reg()应该还有备用的几个注册码, 被我注释掉的那部分,替换一下就行...
或者自己去弄个,一天7分钱吧好像,可能最近用的人多了就没了
后台并不怎么好用, 会很卡的, 熟悉阶段用前台就行




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"fairetamere"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月21日(星期二) 晚上8:10
收件人:&nbsp;"bode135/pydamo"<pydamo@noreply.github.com&gt;;
抄送:&nbsp;"博得"<2248270222@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [bode135/pydamo] ModuleNotFoundError: No module named 'win32com' (#1)





 
跟pycharm版本有关系吗

**Comment by fairetamere** [comment]
谢谢！已经解决啦，感谢



发自我的iPhone


------------------ Original ------------------

**Comment by fairetamere** [comment]
感谢大佬 这几天自己把另外一个插件 乐玩插件也封装起来 回报社会
