### ISSUE TITLE
win10有125%缩放的时候，窗口界面获取不全，有解决思路吗？

### ISSUE THREAD

**Issue by wzk1996** [bode135/pydamo#2]

**Comment by bode135** [comment]
后台截图的话，可查阅一下windows api的截图函数，pywin32包，应该有指定窗口截图的接口。

**Comment by bode135** [comment]
最近研究也涉猎了窗口截图的项目……
也出现了窗口界面获取不全的问题，
解决的思路就是适当扩大一点截图范围……

**Comment by iceMilkAndSugar** [comment]
大漠的文档明确说了要100% 不然会有问题
