### ISSUE TITLE
注释是乱码

### ISSUE THREAD

**Issue by wsfcsk** [bode135/pydamo#3]
你好，来自于你的知乎回答
在demo 里面，注释和字符串是乱码，于是我加了utf-8 编码，还是乱码
class DM:
    def __init__(self):
        try:
            from win32com.client import Dispatch
            #dm = Dispatch('dm.dmsoft')  # 璋冪敤澶ф紶鎻掍欢
            self.dm = Dispatch('dm.dmsoft')  # 璋冪敤澶ф紶鎻掍欢
        except:
            import os
            os.system('regsvr32 dm.dll /s')
            print('娉ㄥ唽dm.dll')
            self.dm = Dispatch('dm.dmsoft')  # 璋冪敤澶ф紶鎻掍欢

        print('鐗堟湰锛�, self.ver(),'锛孖D锛�,self.GetID())

**Comment by bode135** [comment]
……是不是下载的时候出问题了？
可以尝试直接打开dm.py，然后复制源代码过去。

**Comment by wsfcsk** [comment]
解决了，是我的IDE的问题，谢谢
