### ISSUE TITLE
如何新增命令到文件中

### ISSUE THREAD

**Issue by daniel360-luck** [bode135/pydamo#7]
老兄，有很多大漠的命令不能调用，是需要在demo.py里面自己添加后保存吗吗？比如SendString发送文本。
if(1)  :
def SendString(self, hwnd, text):
            return self.dm.SendString(hwnd,text)

**Comment by bode135** [comment]
直接dm. dm就可以，只是没有参数提示。

发自我的iPhone


------------------ 原始邮件 ------------------
发件人: daniel360-luck <notifications@github.com&gt;
发送时间: 2021年2月24日 07:46
收件人: bode135/pydamo <pydamo@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[bode135/pydamo] 如何新增命令到文件中 (#7)

**Comment by daniel360-luck** [comment]
好的，谢谢哈

**Comment by bode135** [comment]
可以直接 dm = Dm(). dm或者dm=dm. dm， 直接调用原dll。
或者参考damo. py的封装格式，在里面加上你想要的函数。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: daniel360-luck <notifications@github.com&gt;
发送时间: 2021年2月24日 07:54
收件人: bode135/pydamo <pydamo@noreply.github.com&gt;
抄送: bode <2248270222@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[bode135/pydamo] 如何新增命令到文件中 (#7)





 
好的，谢谢哈
