### ISSUE TITLE
无法绑定句柄

### ISSUE THREAD

**Issue by hongjiangli1997** [bode135/pydamo#8]
当我想使用后台操作，绑定窗口时，它就会自动退出，请问如何调用api来绑定窗口。

import win32api, win32con, win32gui

from pydamo_0 import Time
from pydamo_0 import DM
from pydamo_0 import Mouse

hwnd = win32gui.FindWindow(None, 'FLYFF')
dm = DM()   # 可指定dm.dll路径DM(path), 若无法使用某些函数dm.f(), 则使用dm.dm.f()来调用.
dm. reg()
ms = Mouse(dm)
tt = Time()

dm_ret = dm.dm.BindWindow(hwnd, 'dx', 'dx', 'dx', 4)
到这自动退出了，这是为什么呢

Process finished with exit code -1073741819 (0xC0000005)

**Comment by bode135** [comment]
...抱歉, 当时收到邮件后忘了回复了.
这个情况应该是我的注册码没钱了- -,
dm插件免费版不能绑定窗口后台使用的.
想后台自动化的话, 需要查看附带的文档, 然后购买注册码...
或者网上和群里去搜一搜免费的试用下.
